---
url: http://asyncdisplaykit.org
name: Huginn China
relative_permalinks: false
markdown: kramdown
timezone: China/Shanghai

safe: true
lsi: false
highlighter: rouge

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: post
      is_post: true

collections:
  docs:
    output: true
